
###
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "email": "admin6@gmail.com",
  "password": "123434"
}

###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin2@gmail.com",
  "password": "123456"
}

###
GET http://localhost:8080/api/v1/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZG1pbjJAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMDgkODdqNjR5Y2NKUkdaM3NOclJnZjcvdXkybW9Lc3NDZHFQLjBCNGcxa0szdlcxa21LbGIvdEMiLCJyb2xlX2NvZGUiOiJSMSIsImlhdCI6MTY5Mjk0MjMzNCwiZXhwIjoxNjkzMzc0MzM0fQ.nt4iBQbyMmelnmQgI_F_HzzZGZpp3s8nDb6gKD8wvc0


###
GET http://localhost:8080/api/v1/insert/

###
GET http://localhost:8080/api/v1/book/?order[]=price&order[]=DESC&limit=2&available[] = 10&available[] = 15

###
GET http://localhost:8080/api/v1/book/
