### GET http://localhost:8080/api/v1/user/

# POST http://localhost:8080/api/v1/auth/register
# Content-Type: application/json

# {
#   "email": "admin2@gmail.com",
#   "password": "123456"
# }

POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "12345326"
}